2023-05-03 08:34:42,398 - freqtrade.loggers - INFO - Verbosity set to 0
2023-05-03 08:34:42,399 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2023-05-03 08:34:42,400 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2023-05-03 08:34:42,400 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2023-05-03 08:34:42,401 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/database/binance/BigTrader2_strategy.sqlite"
2023-05-03 08:34:42,402 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2023-05-03 08:34:42,477 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2023-05-03 08:34:42,478 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2023-05-03 08:34:42,479 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-05-03 08:34:42,486 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-05-03 08:34:42,487 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-05-03 08:34:42,502 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy BigTrader2 from '/freqtrade/user_data/strategies/BigTrader2.py'...
2023-05-03 08:34:42,503 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2023-05-03 08:34:42,504 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2023-05-03 08:34:42,505 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'entry': 'market', 'exit': 'market', 'emergency_exit': 'market', 'force_exit': 'market', 'stoploss': 'market', 'stoploss_on_exchange': True, 'stoploss_on_exchange_interval': 60}.
2023-05-03 08:34:42,505 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2023-05-03 08:34:42,506 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 3000.
2023-05-03 08:34:42,507 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'exit': 5, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2023-05-03 08:34:42,507 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_buying_expired_candle_after' with value in config file: 120.
2023-05-03 08:34:42,508 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 3.
2023-05-03 08:34:42,509 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.09}
2023-05-03 08:34:42,510 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2023-05-03 08:34:42,511 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.5
2023-05-03 08:34:42,512 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2023-05-03 08:34:42,513 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.005
2023-05-03 08:34:42,514 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.029
2023-05-03 08:34:42,515 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
2023-05-03 08:34:42,516 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2023-05-03 08:34:42,517 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2023-05-03 08:34:42,518 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'market', 'exit': 'market', 'emergency_exit': 'market', 'force_exit': 'market', 'stoploss': 'market', 'stoploss_on_exchange': True, 'stoploss_on_exchange_interval': 60}
2023-05-03 08:34:42,519 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'gtc', 'exit': 'gtc'}
2023-05-03 08:34:42,520 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2023-05-03 08:34:42,521 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 3000
2023-05-03 08:34:42,522 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2023-05-03 08:34:42,522 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 60
2023-05-03 08:34:42,523 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'exit': 5, 'exit_timeout_count': 0, 'unit': 'minutes'}
2023-05-03 08:34:42,524 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2023-05-03 08:34:42,525 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: True
2023-05-03 08:34:42,526 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: True
2023-05-03 08:34:42,527 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.01
2023-05-03 08:34:42,528 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2023-05-03 08:34:42,529 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 120
2023-05-03 08:34:42,530 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2023-05-03 08:34:42,531 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2023-05-03 08:34:42,532 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 3
2023-05-03 08:34:42,533 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-05-03 08:34:42,536 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-05-03 08:34:42,537 - freqtrade.exchange.exchange - INFO - Using CCXT 3.0.85
2023-05-03 08:34:42,538 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 195, 'urls': {'api': {'public': 'http://127.0.0.1:8090/api/v3'}}}
2023-05-03 08:34:42,545 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 195, 'urls': {'api': {'public': 'http://127.0.0.1:8090/api/v3'}}}
2023-05-03 08:34:42,551 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-05-03 08:34:42,553 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xffff4d1fe320>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8090): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff4d1fe320>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 601, in fetch
    response = self.session.request(
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8090): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff4d1fe320>: Failed to establish a new connection: [Errno 111] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 491, in _load_markets
    self._markets = self._api.load_markets(params={})
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1459, in load_markets
    markets = self.fetch_markets(params)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 1806, in fetch_markets
    promisesRaw.append(self.publicGetExchangeInfo(params))
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 507, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 7144, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2879, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 654, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binance GET http://127.0.0.1:8090/api/v3/exchangeInfo
2023-05-03 08:34:42,558 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-05-03 08:34:42,558 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 72, in __init__
    self.exchange = ExchangeResolver.load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 34, in load_exchange
    exchange = ExchangeResolver._load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 60, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 186, in __init__
    self.validate_config(config)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 224, in validate_config
    self.validate_stakecurrency(config['stake_currency'])
  File "/freqtrade/freqtrade/exchange/exchange.py", line 526, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-05-03 08:36:30,923 - freqtrade.loggers - INFO - Verbosity set to 0
2023-05-03 08:36:30,924 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2023-05-03 08:36:30,924 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2023-05-03 08:36:30,925 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2023-05-03 08:36:30,926 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/database/binance/BigTrader2_strategy.sqlite"
2023-05-03 08:36:30,927 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2023-05-03 08:36:30,999 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2023-05-03 08:36:31,000 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2023-05-03 08:36:31,001 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-05-03 08:36:31,008 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-05-03 08:36:31,009 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-05-03 08:36:31,023 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy BigTrader2 from '/freqtrade/user_data/strategies/BigTrader2.py'...
2023-05-03 08:36:31,025 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2023-05-03 08:36:31,026 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2023-05-03 08:36:31,026 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'entry': 'market', 'exit': 'market', 'emergency_exit': 'market', 'force_exit': 'market', 'stoploss': 'market', 'stoploss_on_exchange': True, 'stoploss_on_exchange_interval': 60}.
2023-05-03 08:36:31,027 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2023-05-03 08:36:31,028 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 3000.
2023-05-03 08:36:31,028 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'exit': 5, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2023-05-03 08:36:31,029 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_buying_expired_candle_after' with value in config file: 120.
2023-05-03 08:36:31,029 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 3.
2023-05-03 08:36:31,030 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.09}
2023-05-03 08:36:31,031 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2023-05-03 08:36:31,031 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.5
2023-05-03 08:36:31,032 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2023-05-03 08:36:31,033 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.005
2023-05-03 08:36:31,033 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.029
2023-05-03 08:36:31,034 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
2023-05-03 08:36:31,035 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2023-05-03 08:36:31,035 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2023-05-03 08:36:31,036 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'market', 'exit': 'market', 'emergency_exit': 'market', 'force_exit': 'market', 'stoploss': 'market', 'stoploss_on_exchange': True, 'stoploss_on_exchange_interval': 60}
2023-05-03 08:36:31,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'gtc', 'exit': 'gtc'}
2023-05-03 08:36:31,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2023-05-03 08:36:31,038 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 3000
2023-05-03 08:36:31,039 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2023-05-03 08:36:31,039 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 60
2023-05-03 08:36:31,040 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'exit': 5, 'exit_timeout_count': 0, 'unit': 'minutes'}
2023-05-03 08:36:31,041 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2023-05-03 08:36:31,041 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: True
2023-05-03 08:36:31,042 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: True
2023-05-03 08:36:31,042 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.01
2023-05-03 08:36:31,043 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2023-05-03 08:36:31,044 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 120
2023-05-03 08:36:31,044 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2023-05-03 08:36:31,045 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2023-05-03 08:36:31,045 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 3
2023-05-03 08:36:31,046 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-05-03 08:36:31,049 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-05-03 08:36:31,050 - freqtrade.exchange.exchange - INFO - Using CCXT 3.0.85
2023-05-03 08:36:31,051 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 195, 'urls': {'api': {'public': 'http://127.0.0.1:8090/api/v3'}}}
2023-05-03 08:36:31,057 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 195, 'urls': {'api': {'public': 'http://127.0.0.1:8090/api/v3'}}}
2023-05-03 08:36:31,064 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-05-03 08:36:31,065 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xffff5a006350>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8090): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5a006350>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 601, in fetch
    response = self.session.request(
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8090): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5a006350>: Failed to establish a new connection: [Errno 111] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 491, in _load_markets
    self._markets = self._api.load_markets(params={})
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1459, in load_markets
    markets = self.fetch_markets(params)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 1806, in fetch_markets
    promisesRaw.append(self.publicGetExchangeInfo(params))
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 507, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 7144, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2879, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 654, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binance GET http://127.0.0.1:8090/api/v3/exchangeInfo
2023-05-03 08:36:31,069 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-05-03 08:36:31,070 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 72, in __init__
    self.exchange = ExchangeResolver.load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 34, in load_exchange
    exchange = ExchangeResolver._load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 60, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 186, in __init__
    self.validate_config(config)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 224, in validate_config
    self.validate_stakecurrency(config['stake_currency'])
  File "/freqtrade/freqtrade/exchange/exchange.py", line 526, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-05-03 08:57:41,870 - freqtrade.loggers - INFO - Verbosity set to 0
2023-05-03 08:57:41,871 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2023-05-03 08:57:41,871 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2023-05-03 08:57:41,872 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2023-05-03 08:57:41,873 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/database/binance/BigTrader2_strategy.sqlite"
2023-05-03 08:57:41,874 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2023-05-03 08:57:41,970 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2023-05-03 08:57:41,971 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2023-05-03 08:57:41,973 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-05-03 08:57:41,981 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-05-03 08:57:41,983 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-05-03 08:57:42,004 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy BigTrader2 from '/freqtrade/user_data/strategies/BigTrader2.py'...
2023-05-03 08:57:42,005 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2023-05-03 08:57:42,006 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2023-05-03 08:57:42,008 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'entry': 'market', 'exit': 'market', 'emergency_exit': 'market', 'force_exit': 'market', 'stoploss': 'market', 'stoploss_on_exchange': True, 'stoploss_on_exchange_interval': 60}.
2023-05-03 08:57:42,009 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2023-05-03 08:57:42,010 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 3000.
2023-05-03 08:57:42,014 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'exit': 5, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2023-05-03 08:57:42,015 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_buying_expired_candle_after' with value in config file: 120.
2023-05-03 08:57:42,017 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 3.
2023-05-03 08:57:42,018 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.09}
2023-05-03 08:57:42,019 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2023-05-03 08:57:42,020 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.5
2023-05-03 08:57:42,021 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2023-05-03 08:57:42,022 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.005
2023-05-03 08:57:42,023 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.029
2023-05-03 08:57:42,024 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
2023-05-03 08:57:42,025 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2023-05-03 08:57:42,026 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2023-05-03 08:57:42,027 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'market', 'exit': 'market', 'emergency_exit': 'market', 'force_exit': 'market', 'stoploss': 'market', 'stoploss_on_exchange': True, 'stoploss_on_exchange_interval': 60}
2023-05-03 08:57:42,028 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'gtc', 'exit': 'gtc'}
2023-05-03 08:57:42,032 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2023-05-03 08:57:42,033 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 3000
2023-05-03 08:57:42,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2023-05-03 08:57:42,038 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 60
2023-05-03 08:57:42,042 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'exit': 5, 'exit_timeout_count': 0, 'unit': 'minutes'}
2023-05-03 08:57:42,044 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2023-05-03 08:57:42,045 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: True
2023-05-03 08:57:42,046 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: True
2023-05-03 08:57:42,047 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.01
2023-05-03 08:57:42,049 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2023-05-03 08:57:42,050 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 120
2023-05-03 08:57:42,051 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2023-05-03 08:57:42,053 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2023-05-03 08:57:42,054 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 3
2023-05-03 08:57:42,055 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-05-03 08:57:42,059 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-05-03 08:57:42,061 - freqtrade.exchange.exchange - INFO - Using CCXT 3.0.85
2023-05-03 08:57:42,062 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 195, 'urls': {'api': {'public': 'http://127.0.0.1:8090/api/v3'}}}
2023-05-03 08:57:42,070 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 195, 'urls': {'api': {'public': 'http://127.0.0.1:8090/api/v3'}}}
2023-05-03 08:57:42,080 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-05-03 08:57:42,085 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xffff56a02320>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8090): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff56a02320>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 601, in fetch
    response = self.session.request(
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8090): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff56a02320>: Failed to establish a new connection: [Errno 111] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 491, in _load_markets
    self._markets = self._api.load_markets(params={})
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1459, in load_markets
    markets = self.fetch_markets(params)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 1806, in fetch_markets
    promisesRaw.append(self.publicGetExchangeInfo(params))
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 507, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 7144, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2879, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 654, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binance GET http://127.0.0.1:8090/api/v3/exchangeInfo
2023-05-03 08:57:42,093 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-05-03 08:57:42,094 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 72, in __init__
    self.exchange = ExchangeResolver.load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 34, in load_exchange
    exchange = ExchangeResolver._load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 60, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 186, in __init__
    self.validate_config(config)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 224, in validate_config
    self.validate_stakecurrency(config['stake_currency'])
  File "/freqtrade/freqtrade/exchange/exchange.py", line 526, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
